### ISSUE TITLE
Popups don't show on form widgets hidden by branching logic

### ISSUE THREAD

**Issue by scandel** [vanderbilt-redcap/inline-descriptive-popups-module#2]
Hi, 
thanks for this module, it adds a really useful functionnality to REDCap.
It's working fine, except when the linked text is in a form widget hidden by branching logic. 
In this case, the form widget is not visible on page load, and the javascript code on of the module doesn't find it. I played around with the code and found it comes from this line (line 129 in main Class): 

`if(node.parentNode.nodeName == 'SCRIPT' || node.textContent.trim() == '' || !$(node.parentNode).is(":visible")){
`

Removing the last part of the test make the popups work even when under branching logic: 

`if(node.parentNode.nodeName == 'SCRIPT' || node.textContent.trim() == ''){`

I wonder what this test is about and if it would be safe to remove it?

**Comment by mmcev106** [comment]
https://community.projectredcap.org/questions/44482/module-inline-descriptive-popup-popups-dont-like-b.html
